# azure-pipelines.yml
trigger:
  branches:
    include:
      - main  # Branche qui déclenche le pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'

stages:
  - stage: Build_and_Test
    displayName: 'Build & Test Stage'
    jobs:
      - job: Install_and_Run
        displayName: 'Install dependencies and run pipeline'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - script: |
              mkdir -p outputs
              python main.py
            displayName: 'Run main pipeline'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'outputs'
              ArtifactName: 'pipeline_outputs'
              publishLocation: 'Container'
