# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'          # Chemin vers ton pom.xml
    mavenOptions: '-Xmx3072m'        # Mémoire maximale pour Maven
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'           # Version Java à utiliser
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'           # Nettoyer et créer le package
