# File: azure-pipelines.yml
# Pipeline CI pour projet Python - Intelligent e-Learning Chatbot

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'

steps:
# 1️⃣ Checkout du code
- task: Checkout@1
  displayName: 'Checkout repository'

# 2️⃣ Setup Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

# 3️⃣ Installer les dépendances
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# 4️⃣ Lancer les tests
- script: |
    pytest --junitxml=test-results/results.xml
  displayName: 'Run tests'

# 5️⃣ Publier les résultats des tests
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'test-results/results.xml'
    testRunTitle: 'Python Tests'

# 6️⃣ Optionnel: publier artefacts (ex: modèle entraîné)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'models'
    ArtifactName: 'trained-models'
    publishLocation: 'Container'
