trigger:
- main

pool:
  name: Default  # Nom de ton agent auto-hébergé

steps:
# Récupérer le code
- checkout: self
  fetchDepth: 1

# Build Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
